version: "2"

services:
  app:
    build: .
    # Restart the application if it crashes
    #restart: on-failure
    ports:
       - "8080:8080"
    command: /app/server
  db:
    image: postgres
    restart: always
    expose:
      - "5432" # Publishes the port to other containers but NOT to host machine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
